version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: zortv_postgres
    environment:
      POSTGRES_DB: zortv_db
      POSTGRES_USER: zortv_user
      POSTGRES_PASSWORD: zortv_secret_2026
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
